//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lente01.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lente01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Fc Soft.
        /// </summary>
        internal static string AboutAutore {
            get {
                return ResourceManager.GetString("AboutAutore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmut.
        /// </summary>
        internal static string AboutTitolo {
            get {
                return ResourceManager.GetString("AboutTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.0.0a in costruzione .
        /// </summary>
        internal static string AboutVersione {
            get {
                return ResourceManager.GetString("AboutVersione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica lente.
        /// </summary>
        internal static string FormLenteTitolo {
            get {
                return ResourceManager.GetString("FormLenteTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica sorgente.
        /// </summary>
        internal static string FormSorgenteTitolo {
            get {
                return ResourceManager.GetString("FormSorgenteTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lente non realizzabile, valori errati !.
        /// </summary>
        internal static string LenteNonValida {
            get {
                return ResourceManager.GetString("LenteNonValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lente con valori corretti.
        /// </summary>
        internal static string LenteValida {
            get {
                return ResourceManager.GetString("LenteValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgente non corretta !.
        /// </summary>
        internal static string SorgenteNonValida {
            get {
                return ResourceManager.GetString("SorgenteNonValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgente con valori corretti.
        /// </summary>
        internal static string SorgenteValida {
            get {
                return ResourceManager.GetString("SorgenteValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uscire dal programma ?.
        /// </summary>
        internal static string Uscita {
            get {
                return ResourceManager.GetString("Uscita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermare l&apos;uscita....
        /// </summary>
        internal static string UscitaTitolo {
            get {
                return ResourceManager.GetString("UscitaTitolo", resourceCulture);
            }
        }
    }
}
